import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from datetime import datetime
from utils import format_currency, create_summary_dataframe
from visualizations import create_savings_chart, create_roi_chart

def generate_report(results):
    """
    Generate an HTML report based on the calculation results.
    """
    summary_df = create_summary_dataframe(results)

    # Charts
    savings_chart = create_savings_chart(
        results["discipline_savings"],
        results["absenteeism_savings"],
        results["crisis_savings"]
    )
    roi_chart = create_roi_chart(results)

    # Time Savings Calculations
    num_students = results["num_students"]
    discipline_drop = results["discipline_drop"]
    absenteeism_drop = results["absenteeism_drop"]
    crisis_drop = results["crisis_drop"]

    teacher_time_saved_weekly = (
        num_students * discipline_drop * 0.25 +
        num_students * crisis_drop * 0.33 +
        num_students * absenteeism_drop * 0.25
    )
    counselor_time_saved_weekly = (
        num_students * discipline_drop * 0.33 +
        num_students * crisis_drop * 0.5 +
        num_students * absenteeism_drop * 0.33
    )

    teacher_time_saved_annual = teacher_time_saved_weekly * 36
    counselor_time_saved_annual = counselor_time_saved_weekly * 36

    # Charts for Weekly and Annual Time Savings
    weekly_fig = go.Figure(data=[
        go.Bar(name='Teachers', x=['Weekly Time Saved'], y=[teacher_time_saved_weekly]),
        go.Bar(name='Counselors', x=['Weekly Time Saved'], y=[counselor_time_saved_weekly])
    ])
    weekly_fig.update_layout(title='Estimated Weekly Time Savings (Hours)', height=300)

    annual_fig = go.Figure(data=[
        go.Bar(name='Teachers', x=['Annual Time Saved'], y=[teacher_time_saved_annual]),
        go.Bar(name='Counselors', x=['Annual Time Saved'], y=[counselor_time_saved_annual])
    ])
    annual_fig.update_layout(title='Estimated Annual Time Savings (Hours)', height=300)

    weekly_chart_html = weekly_fig.to_html(full_html=False, include_plotlyjs=False)
    annual_chart_html = annual_fig.to_html(full_html=False, include_plotlyjs=False)

    # HTML Template
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
        <style>
            body {{
                font-family: Arial, sans-serif;
                max-width: 1000px;
                margin: auto;
                padding: 20px;
                color: #333;
            }}
            .header, .footer {{
                text-align: center;
                margin-top: 30px;
            }}
            .summary-box {{
                background: #f5f5f5;
                padding: 15px;
                border-left: 5px solid #1565C0;
                margin-bottom: 20px;
            }}
            h1, h2, h3 {{
                color: #1565C0;
            }}
            .chart-container {{
                margin-bottom: 30px;
            }}
        </style>
    </head>
    <body>
        <div class="header">
            <h1>Proactive Mental Health Cost Savings Report</h1>
            <h2>{results["institution_name"]}</h2>
            <p>Generated on {results["timestamp"]}</p>
        </div>

        <div class="summary-box">
            <h3>Executive Summary</h3>
            <p>Based on a student population of <strong>{results["num_students"]:,}</strong>, our analysis indicates a potential total annual savings of <strong>{format_currency(results["total_savings"])}</strong>.</p>
        </div>

        <h3>Cost Savings Breakdown</h3>
        <div class="chart-container">
            {savings_chart.to_html(full_html=False, include_plotlyjs=False)}
        </div>
        <div class="chart-container">
            {roi_chart.to_html(full_html=False, include_plotlyjs=False)}
        </div>

        <h3>Team Time Savings</h3>
        <div class="summary-box">
            <p>Beyond financial savings, implementing proactive mental health strategies can lead to meaningful <strong>time savings</strong> for your staff.</p>
            <p><strong>Teachers:</strong> Estimated <strong>{teacher_time_saved_weekly:.1f} hours/week</strong> and <strong>{teacher_time_saved_annual:.1f} hours/year</strong>.</p>
            <p><strong>Counselors:</strong> Estimated <strong>{counselor_time_saved_weekly:.1f} hours/week</strong> and <strong>{counselor_time_saved_annual:.1f} hours/year</strong>.</p>
        </div>

        <div class="chart-container">{weekly_chart_html}</div>
        <div class="chart-container">{annual_chart_html}</div>

        <div class="footer">
            <p>This report was generated by the Proactive Mental Health Cost Savings Calculator from meetmaro.com.</p>
        </div>
    </body>
    </html>
    """
    return html_content
